[project]
name = "compliance-agents"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "fastapi>=0.115.0",
    "langfuse>=4.7.1",
    "llama-index-core>=0.14.0",
    "llama-index-postprocessor-sbert-rerank>=0.3.0",
    "sentence-transformers>=3.0.0",
    "openinference-instrumentation-llama-index>=4.4.2",
    "llama-index-embeddings-ollama>=0.8.0",
    "llama-index-embeddings-openai-like>=0.3.0",
    "llama-index-llms-ollama>=0.8.0",
    "llama-index-llms-openai-like>=0.3.0",
    "llama-index-vector-stores-qdrant>=0.8.0",
    "pdfminer-six>=20260107",
    "python-dotenv>=1.0.0",
    "qdrant-client>=1.18.0",
    "requests>=2.33.1",
    "uvicorn[standard]>=0.34.0",
]
